server:
  port: 8080
spring:
  application:
    name: rest-with-spring-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  ${DATASOURCE_URL:jdbc:mysql://localhost:3306/rest_with_spring_boot?useTimeZone=true&serverTimeZone=UTC}
    username: ${DATASOURCE_USERNAME:admin}
    password: ${DATASOURCE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: ${DATASOURCE_DBCREATE:update}
      dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: false