name: Continuous Integration With Github Actions

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Hub Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ sectres.DOCKER_PASSWORD }}
  
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build Application JAR
      working-directory: ./rest-with-spring-boot
      run: mvn clean package

    - name: Docker Compose Build Application JAR
      working-directory: ./rest-with-spring-boot
      run: docker compose build 
      
    - name: Push to Docker Hbu Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-app:latest ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-app:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-app:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-app:latest
        
